### ISSUE TITLE
Integration tests for coder-cli

### ISSUE THREAD

**Issue by Russtopia** [cdr/coder-cli#63]
As coder-cli runs against the backend (cdr/enterprise) and depends on its APIs, it would make sense to do some tests of the coder-cli tool itself as part of the main integration checks.

Major features could be tested to ensure they still function, eg:

* sync
* sh
* devurls
  - add
  - update
  - list
  - delete

**Comment by wbobeirne** [comment]
I had also considered this in https://github.com/cdr/enterprise/issues/4230 (Probably should have opened the issue here.) Some upsides of having tests in enterprise is that:
* We'll test changes as the API changes, so we can catch API breaks as a part of the PR in enterprise, instead of tests randomly break in here
* We'll be able to re-use the data scaffolding code for frontend e2e tests, so that you can independently test each method instead of having to test CRUD as one whole flow

**Comment by Russtopia** [comment]
I can close this one and move comments to #4230 if you'd prefer -- let me know, thanks

**Comment by cmoog** [comment]
Closing as the `coder-cli` work is done. The remaining phases involve configuring enterprise namespace deployments and pointing the integrations tests towards mocked APIs.
